matrix:
  include:
    - language: python
      python: 2.7
      install: pip install manticore
      script:
        - cd tests/manticore
        - python operations-concrete-unit-tests.py
    - language: node_js
      node_js: node
      cache: yarn
      script:
        - yarn run ci
      after_script:
        - cat coverage/lcov.info | yarn run coverall
